# Generated by Django 5.0.3 on 2024-04-14 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_certificate_certificate_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='any_file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/assessment_files/test_file'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='assessment_answer_file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/assessment_files/answer_file'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
    ]
